264 v2
ci-group/revolve2 pull request #294
Opened 2023-09-19 11:43 UTC by oliverweissl

V2 accessed through ProperySet

2023-09-20 10:52 UTC, surgura reviewed
First look, will review more throughly once we have resolved the first few things.

So, in general I like that you pulled out the parameters of Bricks, Hinges, and Core from the Actor builder and moved them into the modular robot class. However, I do not like the concept of the PropertySet. I think those properties should be explicitly part of a class for clarity. I have thought about it again, and the v1 and v2 robots could indeed be of the same system and 'compatible'. We would then have BrickV1 (properties set in the class to parameters used by original ActorBuilder), BrickV2 (properties new brick), ActiveHingeV1, ActiveHingeV2. And then CoreV1 and Corev2, where core V2 simply has more slots? Not sure. Maybe for this initial version we can even ignore the fact that there are multiple attachment point of every side, and decide we will also attach on the middle bottom, for simplicitly. We can then make another PR where think about that more. What do you think?

Regarding the genotypes, I think we should have a genotype_v1, and genotype_v2, which builds robots accordingly. Almost always a genotype-phenotype mapping is one to one, and I think it would be clearer for the user.

2023-09-20 10:52 UTC, surgura commented on simulators/mujoco/mypy.ini
> +ignore_missing_imports = True
On my end this is not needed. With a clean virtual environment. Previously this was needed but iirc a recent CV update solved the issues.

2023-09-20 10:52 UTC, surgura commented on examples/robot_bodybrain_ea/config.py
> +POPULATION_SIZE = 10
remove debug

2023-09-20 10:52 UTC, surgura commented on examples/robot_bodybrain_ea/log.txt
remove

2023-09-20 10:52 UTC, surgura commented on examples/robot_bodybrain_ea/rerun.py
remove

2023-09-20 10:52 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/__init__.py
> -from ._body_genotype import BodyGenotype
why?

2023-09-20 10:52 UTC, surgura commented on ci_group/revolve2/ci_group/modular_robots.py
I think we should rename this file to modular_robots_v1.py

2023-09-20 10:52 UTC, surgura commented on ci_group/revolve2/ci_group/modular_robots_v2.py
> +    case = {
While I think it reads nicely, creating the complete case always build every robot for every call to `get`. This is not very efficient. If you want to do this you could e.g. do `"gecko": gecko_v2,`
then
return `case[name]()`
so case the function pointer, but actually only call the function at the return statement.

2023-09-20 10:52 UTC, surgura commented on ci_group/revolve2/ci_group/modular_robots_v2.py
> +        gecko_v2(),
Once this pr is out, let's port most existing morphologies to v2 as well.

2023-09-20 10:52 UTC, surgura commented on ci_group/revolve2/ci_group/modular_robots.py
> +properties = V1PropertySet()
can you make this a private constant? so _PROPERTIES=

2023-09-20 10:52 UTC, surgura commented on ci_group/revolve2/ci_group/modular_robots.py
While we are at it, the v2 file calls gecko gecko_v2. maybe we should rename it here to gecko_v1. just to be super clear.

2023-09-20 10:52 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/_body_develop.py
I would prefer modular_robot_v1 and robot_robot_v2 directories and seperate genotypes. V2 can contain quite a different genotype-phenotype mapping in the future, given the multiple slots on the head.

2023-09-20 10:52 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/_body_genotype.py
> +from revolve2.experimentation.genotypes.cppnwin._multineat_genotype_pickle_wrapper import (
can you keep the relative imports? they are in the same package

2023-09-20 12:33 UTC, surgura commented
Maybe we can introduce (in a next pr maybe?) a 'slot type'. That way the v1 and v2 systems are the same, but modules can only be attached to each other if the attached match or something. just an idea

2023-09-22 08:47 UTC, surgura reviewed
Mostly me nagging about relative imports

2023-09-22 08:47 UTC, surgura commented on ci_group/revolve2/ci_group/modular_robots_v1.py
> +        "gecko": gecko,
can we call the functions spider_v1, babya_v1, etc. mirroring spider_v2 etc

2023-09-22 08:47 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/v1/_body_genotype_orm_v1.py
> +from revolve2.experimentation.genotypes.cppnwin._multineat_rng_from_random import (
can you make this a relative import

2023-09-22 08:47 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/v1/_body_genotype_v1.py
> +from revolve2.experimentation.genotypes.cppnwin._multineat_genotype_pickle_wrapper import (
relative import

2023-09-22 08:47 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/v2/_body_genotype_orm_v2.py
> +from revolve2.experimentation.genotypes.cppnwin._multineat_rng_from_random import (
relative import

2023-09-22 08:47 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/v2/_body_genotype_v2.py
> +from revolve2.experimentation.genotypes.cppnwin._multineat_genotype_pickle_wrapper import (
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/__init__.py
> +from revolve2.modular_robot._active_hinge import ActiveHinge
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_body.py
> +from revolve2.modular_robot._active_hinge import ActiveHinge
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_brain.py
> +from revolve2.modular_robot._body import Body
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_core.py
> +from revolve2.modular_robot._module import Module
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_create_batch_multiple_isolated_robots.py
> +from revolve2.modular_robot._modular_robot import ModularRobot
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_create_batch_single_robot.py
> +from revolve2.modular_robot._modular_robot import ModularRobot
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_modular_robot.py
> +from revolve2.modular_robot._body import Body
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/_module.py
> +from revolve2.modular_robot._not_finalized_error import NotFinalizedError
relative import

2023-09-22 08:47 UTC, surgura commented on modular_robot/revolve2/modular_robot/brains/_morphological_measures.py
> +from revolve2.modular_robot._active_hinge import ActiveHinge
relative import

2023-09-22 13:19 UTC, surgura reviewed
Good steps I think.

2023-09-22 13:19 UTC, surgura commented on modular_robot/revolve2/modular_robot/__init__.py
> +from .brains._morphological_measures import MorphologicalMeasures
this is not part of brains

2023-09-22 13:19 UTC, surgura commented on modular_robot/revolve2/modular_robot/_get_body_states_single_robot.py
> +from revolve2.modular_robot._body import Body
relative import

2023-09-22 13:19 UTC, surgura commented on modular_robot/revolve2/modular_robot/_module.py
> +        Build a module onto the Robot.
can you be more thourough about the description for this function

2023-09-22 13:19 UTC, surgura commented on simulators/mujoco/mypy.ini
> +ignore_missing_imports = True
if you resolve but don't mak changes, can you explain to me why, then i understand the reason for leaving it as is

2023-09-22 13:19 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/v1/_body_develop.py
> +    child = child_type(orientation * (math.pi / 2.0), 0)
can you change this to use keyword arguments. i think it's easy to make mistakes in the order of arguments here because we don't have any type hints

2023-09-22 13:19 UTC, surgura commented on experimentation/revolve2/experimentation/genotypes/cppnwin/modular_robot/v1/_body_develop.py
> +    child = child_type(orientation * (math.pi / 2.0), 0)
furthermore, i think this `,0` is mistake? i don't see it in the init methods of Brick1 etc

2023-09-25 17:52 UTC, surgura requested changes

2023-09-25 17:52 UTC, surgura commented on simulators/mujoco/mypy.ini
> +ignore_missing_imports = True
bump

2023-09-25 17:52 UTC, surgura commented on modular_robot/revolve2/modular_robot/__init__.py
> +from revolve2.modular_robot._morphological_measures import MorphologicalMeasures
relative import

2023-09-25 17:52 UTC, surgura commented on modular_robot/revolve2/modular_robot/_morphological_measures.py
> +from revolve2.modular_robot._active_hinge import ActiveHinge
relative import

2023-09-26 08:51 UTC, surgura approved these changes

2023-09-26 08:56 UTC, oliverweissl commented
bumped to match development branch

2023-09-26 09:01 UTC, merged