new example structure and better docs
ci-group/revolve2 pull request #491
Opened 2024-03-25 14:11 UTC by oliverweissl

2024-03-25 14:16 UTC, oliverweissl commented
@JedMuff The most important part in this PR is whether the structure of examples make sense, also if the readme for the example collections are good to explain their use. If something is unclear pls lmk.

2024-03-26 09:58 UTC, oliverweissl commented on examples/1_simulator_basics/1b_custom_terrain/README.md
should be 1a_

2024-03-26 09:58 UTC, oliverweissl commented on examples/3_experiment_foundations/3c_evaluate_multiple_isolated_robots/README.md
This should be 3b

2024-03-26 09:58 UTC, oliverweissl commented on examples/3_experiment_foundations/3d_evaluate_multiple_interacting_robots/README.md
make it a code block (example name)

2024-03-26 09:58 UTC, oliverweissl commented on examples/3_experiment_foundations/3d_evaluate_multiple_interacting_robots/README.md
x-y displacement

2024-03-26 09:58 UTC, oliverweissl commented on examples/4_example_experiment_setups/4a_simple_ea_xor/main.py
maybe make more comments in the selector classes

2024-03-26 09:58 UTC, oliverweissl commented on examples/4_example_experiment_setups/4c_robot_bodybrain_ea/README.md
should be 3c

2024-03-27 12:50 UTC, JedMuff requested changes
Overall I like this structure and the comments made to the code to make it more like a tutorial.

2024-03-27 13:07 UTC, oliverweissl commented
@JedMuff 
Thanks for the feedback! I adjusted,.

2024-03-27 13:40 UTC, JedMuff approved these changes

2024-03-27 15:22 UTC, merged